decidim-admin/config/routes.rb
# frozen_string_literal: true

Decidim::Admin::Engine.routes.draw do
  constraints(->(request) { Decidim::Admin::OrganizationDashboardConstraint.new(request).matches? }) do
    resource :organization, only: [:edit, :update], controller: "organization"
    resources :participatory_process_groups
    resources :participatory_processes do
      resource :publish, controller: "participatory_process_publications", only: [:create, :destroy]
      resources :copies, controller: "participatory_process_copies", only: [:new, :create]

      resources :categories

      resources :steps, controller: "participatory_process_steps" do
        resource :activate, controller: "participatory_process_step_activations", only: [:create, :destroy]
        collection do
          post :ordering, to: "participatory_process_step_ordering#create"
        end
      end
      resources :user_roles, controller: "participatory_process_user_roles"
      resources :attachments, controller: "participatory_process_attachments"

      resources :features do
        resource :permissions, controller: "feature_permissions"
        member do
          put :publish
          put :unpublish
        end
        resources :exports, only: :create
      end

      resources :moderations do
        member do
          put :unreport
          put :hide
        end
      end
    end

    scope "/participatory_processes/:participatory_process_id/features/:feature_id/manage" do
      Decidim.feature_manifests.each do |manifest|
        next unless manifest.admin_engine

        constraints Decidim::CurrentFeature.new(manifest) do
          mount manifest.admin_engine, at: "/", as: "decidim_admin_#{manifest.name}"
        end
      end

      get "/", to: redirect("/404"), as: :manage_feature
    end

    resources :static_pages
    resources :scopes, except: [:show]
    resources :users, except: [:edit, :update], controller: "users" do
      member do
        post :resend_invitation, to: "users#resend_invitation"
      end
    end

    resources :newsletters do
      member do
        get :preview
        post :deliver
      end
    end

    resources :user_groups, only: [:index] do
      member do
        put :verify
      end
    end

    root to: "dashboard#show"
  end
end

decidim-admin/app/controllers/decidim/admin/categories_controller.rb
# frozen_string_literal: true

require_dependency "decidim/admin/application_controller"

module Decidim
  module Admin
    # Controller that allows managing categories.
    #
    class CategoriesController < ApplicationController
      include Concerns::ParticipatoryProcessAdmin

      def index
        authorize! :read, Decidim::Category
      end

      def new
        authorize! :create, Decidim::Category
        @form = form(CategoryForm).from_params({}, current_process: participatory_process)
      end

      def create
        authorize! :create, Decidim::Category
        @form = form(CategoryForm).from_params(params, current_process: participatory_process)

        CreateCategory.call(@form, participatory_process) do
          on(:ok) do
            flash[:notice] = I18n.t("categories.create.success", scope: "decidim.admin")
            redirect_to participatory_process_categories_path(participatory_process)
          end

          on(:invalid) do
            flash.now[:alert] = I18n.t("categories.create.error", scope: "decidim.admin")
            render :new
          end
        end
      end

      def edit
        @category = collection.find(params[:id])
        authorize! :update, @category
        @form = form(CategoryForm).from_model(@category, current_process: participatory_process)
      end

      def update
        @category = collection.find(params[:id])
        authorize! :update, @category
        @form = form(CategoryForm).from_params(params, current_process: participatory_process)

        UpdateCategory.call(@category, @form) do
          on(:ok) do
            flash[:notice] = I18n.t("categories.update.success", scope: "decidim.admin")
            redirect_to participatory_process_categories_path(participatory_process)
          end

          on(:invalid) do
            flash.now[:alert] = I18n.t("categories.update.error", scope: "decidim.admin")
            render :edit
          end
        end
      end

      def show
        @category = collection.find(params[:id])
        authorize! :read, @category
      end

      def destroy
        @category = collection.find(params[:id])
        authorize! :destroy, @category

        DestroyCategory.call(@category) do
          on(:ok) do
            flash[:notice] = I18n.t("categories.destroy.success", scope: "decidim.admin")
          end

          on(:invalid) do
            flash[:alert] = I18n.t("categories.destroy.error", scope: "decidim.admin")
          end

          redirect_back(fallback_location: participatory_process_categories_path(participatory_process))
        end
      end

      private

      def collection
        @collection ||= participatory_process.categories.includes(:subcategories)
      end
    end
  end
end

decidim-admin/app/views/decidim/admin/categories/_form.html.erb
<div class="card">
  <div class="card-divider">
    <h2 class="card-title"><%= title %></h2>
  </div>

  <div class="card-section">
    <div class="row column">
      <%= form.translated :text_field, :name, autofocus: true %>
    </div>

    <div class="row column">
      <%= form.translated :editor, :description %>
    </div>

    <div class="row column">
      <%= form.label :parent_id %>
      <%= select :category, :parent_id, @form.parent_categories.collect { |c| [c.name[current_organization.default_locale], c.id] }, include_blank: true %>
    </div>
  </div>
</div>

decidim-admin/app/views/decidim/admin/categories/edit.html.erb
<%= decidim_form_for(@form, url: participatory_process_category_path(@category.participatory_process, @category), html: { class: "form edit_participatory_process_category" }) do |f| %>
  <%= render partial: 'form', object: f, locals: { title: t('.title') } %>

  <div class="button--double form-general-submit">
    <%= f.submit t(".update") %>
  </div>
<% end %>

decidim-admin/app/views/decidim/admin/categories/index.html.erb
<div class="card" id="categories">
  <div class="card-divider">
    <h2 class='card-title'>
      <%= t(".categories_title", scope: "decidim.admin") %>
      <% if can? :create, Decidim::Category %>
        <%= link_to t("actions.new", scope: "decidim.admin", name: t("models.category.name", scope: "decidim.admin")), new_participatory_process_category_path(participatory_process), class: 'button tiny button--title new' %>
      <% end %>
    </h2>
  </div>

  <div class="card-section">
     <% if participatory_process.categories.any? %>
      <div class="table-scroll">
        <table class="table-list">
          <thead>
            <tr>
              <th><%= t("activemodel.attributes.category.name") %></th>
              <th class="actions"></th>
            </tr>
          </thead>
          <tbody>
            <% participatory_process.categories.first_class.each do |category| %>
              <tr>
                <td>
                  <%= link_to translated_attribute(category.name), edit_participatory_process_category_path(participatory_process, category) %><br />
                </td>
                <td class="table-list__actions">
                  <% if can? :update, category %>
                    <%= icon_link_to "pencil", edit_participatory_process_category_path(participatory_process, category), t("actions.edit", scope: "decidim.admin"), class: "action-icon--edit" %>
                  <% end %>

                  <% if can? :destroy, category %>
                    <%= icon_link_to "circle-x", participatory_process_category_path(participatory_process, category), t("actions.destroy", scope: "decidim.admin"), class: "action-icon--remove", method: :delete, data: { confirm: t("actions.confirm_destroy", scope: "decidim.admin") } %>
                  <% end %>
                </td>
              </tr>
              <% category.subcategories.each do |subcategory| %>
                <tr class="extra__table-list__subcategory">
                  <td>
                    <%= link_to translated_attribute(subcategory.name), edit_participatory_process_category_path(participatory_process, subcategory) %><br />
                  </td>
                  <td class="table-list__actions">
                  <% if can? :update, subcategory %>
                    <%= icon_link_to "pencil", edit_participatory_process_category_path(participatory_process, subcategory), t("actions.edit", scope: "decidim.admin"), class: "action-icon--edit" %>
                  <% end %>

                  <% if can? :destroy, subcategory %>
                    <%= icon_link_to "circle-x", participatory_process_category_path(participatory_process, subcategory), t("actions.destroy", scope: "decidim.admin"), class: "action-icon--remove", method: :delete, data: { confirm: t("actions.confirm_destroy", scope: "decidim.admin") } %>
                  <% end %>
                  </td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    <% end %>
  </div>
</div>

decidim-admin/app/views/decidim/admin/categories/new.html.erb
<%= decidim_form_for(@form, url: participatory_process_categories_path(participatory_process), html: { class: "form new_participatory_process_category" }) do |f| %>
  <%= render partial: 'form', object: f, locals: { title: t('.title') } %>

  <div class="button--double form-general-submit">
    <%= f.submit t(".create") %>
  </div>
<% end %>

decidim-admin/app/views/decidim/admin/categories/show.html.erb
<h3><%= translated_attribute(@category.name) %></h3>

<div class="actions">
  <hr />
  <%= link_to t("decidim.admin.actions.edit"), ['edit', participatory_process, @category] if can? :update, @category %>
  <%= link_to t("decidim.admin.actions.destroy"), [participatory_process, @category], method: :delete, class: "alert button", data: { confirm: t("decidim.admin.actions.confirm_destroy") } if can? :destroy, @category %>
</div>

<dl>
  <%= display_for @category,
    :name,
    :description
    %>
</dl>