decidim-core/config/routes.rb
# frozen_string_literal: true

Decidim::Core::Engine.routes.draw do
  mount Decidim::Api::Engine => "/api"

  devise_for :users,
             class_name: "Decidim::User",
             module: :devise,
             router_name: :decidim,
             controllers: {
               invitations: "decidim/devise/invitations",
               sessions: "decidim/devise/sessions",
               confirmations: "decidim/devise/confirmations",
               registrations: "decidim/devise/registrations",
               passwords: "decidim/devise/passwords",
               omniauth_callbacks: "decidim/devise/omniauth_registrations"
             }

  devise_scope :user do
    post "omniauth_registrations" => "devise/omniauth_registrations#create"
  end

  resource :locale, only: [:create]

  resources :participatory_process_groups, only: :show, path: "processes_groups"
  resources :participatory_processes, only: [:index, :show], path: "processes" do
    resources :participatory_process_steps, only: [:index], path: "steps"
    resource :participatory_process_widget, only: :show, path: "embed"
  end

  scope "/processes/:participatory_process_id/f/:feature_id" do
    Decidim.feature_manifests.each do |manifest|
      next unless manifest.engine

      constraints Decidim::CurrentFeature.new(manifest) do
        mount manifest.engine, at: "/", as: "decidim_#{manifest.name}"
      end
    end

    get "/", to: redirect("/404"), as: :feature
  end

  authenticate(:user) do
    resources :authorizations, only: [:new, :create, :index] do
      collection do
        get :first_login
      end
    end
    resource :account, only: [:show, :update], controller: "account"
    resource :notifications_settings, only: [:show, :update], controller: "notifications_settings"
    resources :own_user_groups, only: [:index]
  end

  resources :pages, only: [:index, :show], format: false

  get "/static_map", to: "static_map#show", as: :static_map
  get "/cookies/accept", to: "cookie_policy#accept", as: :accept_cookies

  match "/404", to: "pages#show", id: "404", via: :all
  match "/500", to: "pages#show", id: "500", via: :all

  if Rails.env.development? && defined?(LetterOpenerWeb::Engine)
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resource :report, only: [:create]

  root to: "pages#show", id: "home"
end

decidim-core/app/views/pages/home/_extended.html.erb
<section class="extended">
  <div class="wrapper-home home-section">
    <div class="row column text-center">
      <h3 class="heading2"><%= t(".how_to_participate") %></h3>
    </div>
    <div class="row small-up-1 medium-up-3 home-bullets">
      <div class="column">
        <div class="home-bullet">
          <div class="home-bullet__icon">
            <%= icon "meetings" %>
          </div>
          <div class="home-bullet__desc">
            <h4 class="heading6"><%= t(".meetings") %></h4>
            <p><%= t(".meetings_explanation") %></p>
          </div>
        </div>
      </div>
      <div class="column">
        <div class="home-bullet">
          <div class="home-bullet__icon">
            <%= icon "debates" %>
          </div>
          <div class="home-bullet__desc">
            <h4 class="heading6"><%= t(".debates") %></h4>
            <p><%= t(".debates_explanation") %></p>
          </div>
        </div>
      </div>
      <div class="column">
        <div class="home-bullet">
          <div class="home-bullet__icon">
            <%= icon "proposals" %>
          </div>
          <div class="home-bullet__desc">
            <h4 class="heading6"><%= t(".proposals") %></h4>
            <p><%= t(".proposals_explanation") %></p>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="columns small-centered small-10
                smallmedium-8 medium-6 large-4">
        <%= link_to t(".more_info"), page_path("faq"), class: "button expanded hollow button--sc" %>
      </div>
    </div>
  </div>
</section>

decidim-core/app/views/pages/home/_footer_sub_hero.html.erb
<section class="footer__subhero extended subhero home-section">
  <div class="row">
    <div class="columns small-centered large-10">
      <h2 class="heading3"><%= t(".footer_sub_hero_headline", organization: current_organization.name) %></h2>
      <h5 class="heading4"><%== t(".footer_sub_hero_body") %></h5>
      <%= link_to new_user_registration_path, class: "button--sc link subhero-cta" do %>
        <%= t(".register") %>
        <%= icon "chevron-right", aria_hidden: true %>
      <% end %>
    </div>
  </div>
</section>

decidim-core/app/views/pages/home/_hero.html.erb
<section class="extended hero" style="background-image:url(<%= current_organization.homepage_image.url %>);">
  <div class="hero__container">
    <div class="row">
      <div class="columns small-centered large-10">
        <h1 class="text-highlight heading1 hero-heading">
          <% if translated_attribute(current_organization.welcome_text).blank? %>
            <%= t('.welcome', organization: current_organization.name) %>
          <% else %>
            <%== translated_attribute current_organization.welcome_text %>
          <% end %>
        </h1>
      </div>
    </div>
    <div class="row">
      <div class="columns small-centered small-6 medium-4 mediumlarge-3">
        <%= link_to t('.participate'), participatory_processes_path, class: "hero-cta button expanded large button--sc" %>
      </div>
    </div>
  </div>
</section>

decidim-core/app/views/pages/home/_highlighted_processes.html.erb
<section class="wrapper-home">
  <div class="row">
    <h3 class="section-heading"><%= t(".active_processes") %></h3>
    <div class="row collapse">
      <div class="row small-up-1 smallmedium-up-2 mediumlarge-up-3
                  large-up-4 card-grid">
        <% highlighted_participatory_processes.each do |process| %>
          <div class="column">
            <article class="card card--process card--mini">
              <%= link_to participatory_process_path(process), class: "card__link" do %>
                <div class="card__image-top"
                     style="background-image:url(<%= process.hero_image.url %>)"></div>
              <% end %>
              <div class="card__content">
                <%= link_to participatory_process_path(process), class: "card__link" do %>
                  <h4 class="card__title"><%= translated_attribute process.title %></h4>
                <% end %>
                <% if process.active_step %>
                  <span class="card--process__small">
                    <%= t(".active_step") %>
                    <strong><%= translated_attribute process.active_step.title %></strong>
                  </span>
                <% end %>
              </div>
            </article>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="columns small-centered small-12
                smallmedium-8 medium-6 large-4">
      <%= link_to t(".see_all_processes"), participatory_processes_path, class: "button expanded hollow button--sc home-section__cta" %>
    </div>
  </div>
</section>

decidim-core/app/views/pages/home/_statistics.html.erb
<section class="extended" id="statistics">
  <div class="wrapper-home">
    <div class="row column text-center">
      <h3 class="heading2"><%= t(".headline", organization: current_organization.name) %></h3>
    </div>
    <div class="row">
      <div class="columns small-centered mediumlarge-10 large-8">
        <div class="home-pam">
          <%= stats.highlighted %>
          <%= stats.not_highlighted %>
        </div>
      </div>
    </div>
  </section>

decidim-core/app/views/pages/home/_sub_hero.html.erb
  <section class="extended subhero home-section">
    <div class="row">
      <div class="columns small-centered large-10">
        <h2 class="heading3"><%== translated_attribute current_organization.description %></h2>
        <%= link_to new_user_registration_path, class: "button--sc link subhero-cta" do %>
          <%= t(".register") %>
          <%= icon "chevron-right", aria_hidden: true %>
        <% end %>
      </div>
    </div>
  </section>